"""NYXARA · growth/immunology.py — autonomous cybernetic immunology (🦠, B).

A standard test suite only catches the failures someone already wrote a test for. This module gives
NYXARA an **Attacker Agent** that proactively hammers her *own* callables with boundary and mutated
inputs to surface crashes and latent bugs **before** they ever trigger in production, then turns each
finding into a **permanent regression test** and routes the reproduction to the self-debugger for a fix.

Design (honest and bounded):

* Only **pure, public, type-annotated** callables of an *allowlisted* module are fuzzed — never
  I/O-mutating, guard, or identity/master code (excluded outright).
* A finding is an **unexpected crash**: an exception that is *not* the contract's own
  ``TypeError``/``ValueError`` on out-of-contract input — e.g. ``IndexError``, ``ZeroDivisionError``,
  ``RecursionError``. A ``TypeError`` on a wrong-typed argument is *not* a bug.
* A **nondeterminism** finding: the same input yields different results across repeated calls
  (a cheap race/impurity proxy — not a full concurrency model checker).

Each finding yields a ``pytest`` regression snippet that pins the input, so once fixed it is guarded
forever. Pure standard library; no LLM; it only *judges* callables — it edits no source itself (the fix
is authored by :mod:`nyxara.growth.self_debugger` under the usual gauntlet).
"""

from __future__ import annotations

import inspect
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence

__all__ = ["Finding", "ImmuneReport", "Immunologist", "fuzz_callable"]

# modules NYXARA must never fuzz (character/safety core, and side-effecting subsystems)
_EXCLUDE_PREFIXES = ("nyxara.guard", "nyxara.identity", "nyxara.server", "nyxara.senses",
                     "nyxara.agency.net_request")

# out-of-contract inputs legitimately raise these — not bugs
_CONTRACT_ERRORS = (TypeError, ValueError)

# boundary batteries per annotated type
_BOUNDARY: Dict[Any, List[Any]] = {
    int: [0, 1, -1, 2, -2, 7, -7, 10**6, -(10**6)],
    float: [0.0, 1.0, -1.0, 1e-9, 1e9, -1e9, 0.5],
    str: ["", " ", "a", "0", "\n", "x" * 64, "😀", "\x00"],
    bool: [True, False],
    list: [[], [0], [1, 2, 3], [-1, -2], list(range(32)), [0, 0, 0]],
    dict: [{}, {"k": 1}, {"a": 0, "b": -1}],
    tuple: [(), (0,), (1, 2, 3)],
}
_UNTYPED = [0, 1, -1, "", "x", [], [1, 2, 3], None, 0.5, True]


@dataclass
class Finding:
    """One discovered defect in a callable."""

    module: str
    qualname: str
    kind: str                       # "crash" | "nondeterminism"
    args: tuple
    detail: str

    def to_dict(self) -> Dict[str, Any]:
        return {"module": self.module, "qualname": self.qualname, "kind": self.kind,
                "args": repr(self.args), "detail": self.detail}

    def regression_test(self) -> str:
        """A permanent pytest snippet pinning this finding (added to the Safety Gauntlet on fix)."""
        mod = self.module
        fn = self.qualname
        args = ", ".join(repr(a) for a in self.args)
        safe = fn.replace(".", "_")
        return (f"def test_immunology_{safe}_regression():\n"
                f"    # auto-generated by NYXARA immunology — {self.kind}: {self.detail}\n"
                f"    from {mod} import {fn.split('.')[0]}\n"
                f"    {fn}({args})   # must not raise / must be deterministic once fixed\n")


@dataclass
class ImmuneReport:
    module: str
    scanned: int = 0
    findings: List[Finding] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {"module": self.module, "scanned": self.scanned,
                "findings": [f.to_dict() for f in self.findings]}


def _inputs_for(param: inspect.Parameter) -> List[Any]:
    ann = param.annotation
    if ann in _BOUNDARY:
        return _BOUNDARY[ann]
    origin = getattr(ann, "__origin__", None)
    if origin in _BOUNDARY:
        return _BOUNDARY[origin]
    return _UNTYPED


def _arg_batteries(fn: Callable, *, max_cases: int) -> List[tuple]:
    """A bounded set of positional-arg tuples from the annotated signature."""
    try:
        sig = inspect.signature(fn)
    except (TypeError, ValueError):
        return []
    params = [p for p in sig.parameters.values()
              if p.kind in (p.POSITIONAL_ONLY, p.POSITIONAL_OR_KEYWORD)
              and p.default is inspect._empty]
    if not params:
        return [()]                    # nullary (all-defaulted) callable — one no-arg probe
    # cartesian would explode; instead vary one parameter at a time around a benign baseline
    baselines = [(_inputs_for(p)[0] if _inputs_for(p) else None) for p in params]
    cases: List[tuple] = [tuple(baselines)]
    for i, p in enumerate(params):
        for v in _inputs_for(p):
            case = list(baselines)
            case[i] = v
            cases.append(tuple(case))
            if len(cases) >= max_cases:
                return cases
    return cases


def fuzz_callable(fn: Callable, *, module: str = "", qualname: str = "",
                  max_cases: int = 40) -> List[Finding]:
    """Fuzz one callable with boundary/mutated inputs. Returns crash + nondeterminism findings."""
    qualname = qualname or getattr(fn, "__name__", "fn")
    module = module or getattr(fn, "__module__", "")
    findings: List[Finding] = []
    for args in _arg_batteries(fn, max_cases=max_cases):
        try:
            first = fn(*args)
        except _CONTRACT_ERRORS:
            continue                    # out-of-contract input — legitimate, not a bug
        except RecursionError as exc:
            findings.append(Finding(module, qualname, "crash", args, "RecursionError"))
            continue
        except Exception as exc:  # noqa: BLE001 — any other exception is an unexpected crash
            findings.append(Finding(module, qualname, "crash", args,
                                    f"{exc.__class__.__name__}: {exc}"))
            continue
        # nondeterminism probe (cheap impurity/race proxy)
        try:
            second = fn(*args)
            if first != second and repr(first) != repr(second):
                findings.append(Finding(module, qualname, "nondeterminism", args,
                                        f"{first!r} != {second!r} on repeat"))
        except Exception:  # noqa: BLE001 — a second-call divergence is itself a signal, but keep it simple
            findings.append(Finding(module, qualname, "nondeterminism", args,
                                    "raised only on the second identical call"))
    return findings


class Immunologist:
    """Scan an allowlisted module's public callables for latent defects."""

    def __init__(self, *, max_cases: int = 40) -> None:
        self.max_cases = max_cases

    @staticmethod
    def is_allowed(module_name: str) -> bool:
        return not any(module_name.startswith(p) for p in _EXCLUDE_PREFIXES)

    def scan_module(self, module: Any) -> ImmuneReport:
        """Fuzz every public, top-level function of ``module`` (an imported module object)."""
        name = getattr(module, "__name__", str(module))
        report = ImmuneReport(module=name)
        if not self.is_allowed(name):
            return report              # excluded core — never fuzzed
        for attr, obj in vars(module).items():
            if attr.startswith("_"):
                continue
            if not inspect.isfunction(obj):
                continue
            if getattr(obj, "__module__", None) != name:
                continue               # re-exported from elsewhere — skip
            report.scanned += 1
            report.findings.extend(
                fuzz_callable(obj, module=name, qualname=attr, max_cases=self.max_cases))
        return report
