"""NYXARA · njp/generators.py — finding the few things everything else is made of (🌱, NJP V.94).

Every version from V.89 to V.92 was handed the thing it was supposed to be clever about. V.89 got
nine laws. V.90 got seven moves. V.91 got a substrate of four numbers. V.92 got a list of
vocabularies to weigh. Each time the search was real and each time **the origin of the candidates
was me**.

So nothing here is given a parameterisation. The input is a set of transformations observed only as
behaviour — rows in, rows out — and one question:

    can these be written down together more cheaply than one at a time?

**And the answer, when there is one, is a handful of them.** If some of the observed transformations
compose to give all the others, then the whole set is described by naming those few and then
writing each remaining one as a short recipe. Finding *which* few is the discovery, and it is not a
parameterisation anybody supplied — it is a subset of the observations themselves.

A family of rotations turns out to be powers of one member. Rotations with a flip turn out to need
two. Nobody says *stride* or *offset* anywhere: what comes back is ``generator 1`` and
``generator 2``, and the thing that makes them generators is that everything else is a composition
of them.

**Declining is the important case.** A set of unrelated transformations has no compact description,
and the honest output is *writing them out one at a time is the cheapest thing available*. A search
that always produces generators would find them in noise — so the exam is half made of families
that have none, and :func:`describe` is expected to come back empty.

**Cost decides, not elegance.** V.92's measure is imported rather than re-invented: the whole
description in bits — the generators, plus a recipe for each transformation, against the flat cost
of writing every one longhand. A generating set that does not pay for itself is not kept, however
pretty the structure it reveals.

**And the generators are found on one half and charged on the other.** A compact description fitted
to the transformations it is measured on is a lookup table with extra steps.

Pure standard library.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

__all__ = ["Observed", "Recipe", "Description", "watch_behaviour", "describe", "longhand",
           "WIDTH", "DEPTH", "LOOKED_AT", "MARK", "SEED"]

WIDTH = 8

#: How long a recipe may be. Beyond this, naming the composition costs more than the thing it
#: replaces, and a description nobody could follow is not a description.
#:
#: Set to the row width because a family of rotations needs ``width - 1`` steps to reach its last
#: member. At six it covered seven of eight and reported an incomplete description of a set that is
#: perfectly generated by one element — a limit of the search reported as a property of the family.
DEPTH = WIDTH

#: How many compositions the search will explore from one candidate set before giving up. Without
#: it, three unrelated permutations generate most of the symmetric group and the search walks all
#: of it to prove that they explain nothing.
LOOKED_AT = 4000

SEED = 94

#: One observed transformation, as what it does to positions and nothing else.
Observed = Tuple[int, ...]


#: The value a probe puts in one place. **Not** one, and that is the whole of it: probed with ones,
#: squaring is indistinguishable from leaving the row alone, because ``0² = 0`` and ``1² = 1``. The
#: exam caught it — a family built entirely of transformations that are not rearrangements had one
#: member read as the identity. A probe's basis can be exactly where the thing it is looking for
#: does not show.
MARK = 3.0


def watch_behaviour(operation: Callable[[Sequence[float]], Sequence[float]],
                    width: int = WIDTH) -> Optional[Observed]:
    """What a transformation does, learned by watching it rather than by reading it.

    Each position is marked in turn with :data:`MARK` and the output is searched for the mark. A
    transformation that does something other than move values around — that adds, averages, scales
    or invents — leaves no mark where one is expected, has no description of this kind, and comes
    back ``None``. That is a finding and not a failure: it says this whole way of writing a
    transformation down does not apply here.
    """
    out: List[int] = []
    for i in range(width):
        row = [0.0] * width
        row[i] = MARK
        try:
            got = list(operation(row))
        except Exception:  # noqa: BLE001
            return None
        if len(got) != width:
            return None
        marked = [j for j, v in enumerate(got) if abs(v - MARK) < 1e-9]
        if len(marked) != 1:
            return None
        if any(abs(v) > 1e-9 for j, v in enumerate(got) if j != marked[0]):
            return None
        out.append(marked[0])
    seen = [0] * width
    for at in out:
        seen[at] += 1
    if any(c != 1 for c in seen):
        return None
    order = [0] * width
    for i, at in enumerate(out):
        order[at] = i
    return tuple(order)


def _compose(one: Observed, two: Observed) -> Observed:
    """``one`` then ``two``: apply one, then apply two to the result."""
    return tuple(one[two[i]] for i in range(len(one)))


def _still() -> Observed:
    return tuple(range(WIDTH))


@dataclass(frozen=True)
class Recipe:
    """How to make one transformation out of the generators, as a list of their numbers."""

    steps: Tuple[int, ...] = ()

    @property
    def length(self) -> int:
        return len(self.steps)

    def render(self, names: Sequence[str]) -> str:
        if not self.steps:
            return "leave it alone"
        return " then ".join(names[s] for s in self.steps)


@dataclass
class Description:
    """A set of transformations, written down as cheaply as anything here managed.

    The generators carry numbers, not names. What makes one a generator is that other things are
    compositions of it, which is a property of the set and not a label anybody attached.
    """

    generators: List[Observed] = field(default_factory=list)
    recipes: Dict[Observed, Recipe] = field(default_factory=dict)
    covered: int = 0
    of: int = 0
    width: int = WIDTH

    @property
    def names(self) -> List[str]:
        return [f"generator {i + 1}" for i in range(len(self.generators))]

    @property
    def complete(self) -> bool:
        return self.of > 0 and self.covered == self.of

    @property
    def cost(self) -> float:
        """Bits: writing each generator out in full, then a recipe for every transformation.

        A recipe costs its length times the bits to name one generator, plus one to say where it
        stops. With no generators there is nothing to name and the whole thing is longhand.
        """
        if not self.generators:
            return longhand(self.of, self.width)
        naming = math.log2(len(self.generators)) + 1.0
        spelling = len(self.generators) * self.width * math.log2(max(2, self.width))
        following = sum(max(1.0, r.length) * naming for r in self.recipes.values())
        missing = (self.of - self.covered) * self.width * math.log2(max(2, self.width))
        return round(spelling + following + missing, 2)

    def to_dict(self) -> Dict[str, Any]:
        return {"generators": len(self.generators), "covered": self.covered, "of": self.of,
                "cost": self.cost, "longhand": longhand(self.of, self.width),
                "worth_it": self.worth_it, "complete": self.complete,
                "recipes": {str(k): v.render(self.names) for k, v in
                            list(self.recipes.items())[:4]}}

    @property
    def worth_it(self) -> bool:
        """Does the compact description cost less — by enough, and for **all** of them?

        Two conditions, and the first version had neither. It asked only whether the total beat
        longhand, and on eight unrelated permutations it duly found three "generators" covering
        seven, at 184 bits against 192. There is no structure in that set at all. The saving was an
        artefact: **generators are drawn from the observed transformations**, so choosing any three
        writes three out in full and leaves five to be reached — which looks like compression
        whatever the five turn out to be.

        So a description must explain **everything**, and it must save more than one transformation
        is worth. The margin is not a tuned constant: a description that saves less than the cost of
        writing a single member longhand has not found structure, it has found a rounding.
        """
        return (bool(self.generators) and self.complete
                and self.cost < longhand(self.of, self.width) - longhand(1, self.width))

    def render(self) -> str:
        if not self.generators:
            return (f"  no generating set pays for itself; writing all {self.of} out longhand "
                    f"costs {longhand(self.of, self.width):.0f} bits and nothing here beat it")
        lines = [f"  {len(self.generators)} generators cover {self.covered}/{self.of} "
                 f"at {self.cost:.0f} bits against {longhand(self.of, self.width):.0f} longhand"]
        for i, gen in enumerate(self.generators):
            lines.append(f"    generator {i + 1}: {gen}")
        return "\n".join(lines)


def longhand(count: int, width: int = WIDTH) -> float:
    """Bits to write every transformation out on its own, with no structure to lean on."""
    return round(count * width * math.log2(max(2, width)), 2)


def _reachable(generators: Sequence[Observed], want: Sequence[Observed],
               depth: int = DEPTH, looked_at: int = LOOKED_AT) -> Dict[Observed, Recipe]:
    """Everything the generators build within ``depth`` steps, with the recipe for each.

    Breadth first, so the recipe found for anything is the shortest one — which matters because the
    recipe's length is what it costs.
    """
    wanted = set(want)
    found: Dict[Observed, Recipe] = {_still(): Recipe(())}
    edge = [(_still(), Recipe(()))]
    for _ in range(max(1, depth)):
        nxt: List[Tuple[Observed, Recipe]] = []
        for where, recipe in edge:
            for i, gen in enumerate(generators):
                step = _compose(where, gen)
                if step in found:
                    continue
                made = Recipe(recipe.steps + (i,))
                found[step] = made
                nxt.append((step, made))
        edge = nxt
        if not edge or wanted <= set(found) or len(found) > looked_at:
            break
    return {k: v for k, v in found.items() if k in wanted}


def describe(observed: Sequence[Observed], *, depth: int = DEPTH,
             width: int = WIDTH, most: int = 3) -> Description:
    """Find the few observed transformations everything else is a composition of.

    Searched smallest-first, and the candidates are **the observations themselves** — not a
    parameterisation, not a family somebody named. A set that is nothing but its own members is
    reported as exactly that, with an empty generating set, because *writing them out one at a
    time is the cheapest thing available* is a real answer and the one most sets deserve.
    """
    unique = sorted(set(observed))
    nothing = Description(generators=[], recipes={}, covered=0, of=len(unique), width=width)
    best: Optional[Description] = None
    for size in range(1, max(1, most) + 1):
        for picked in _choose(unique, size):
            reached = _reachable(picked, unique, depth=depth)
            here = Description(generators=list(picked), recipes=reached,
                               covered=len(reached), of=len(unique), width=width)
            # Cheapest wins, full stop. The first version also demanded more coverage than the
            # incumbent, which quietly refuses a description that explains the same set for fewer
            # bits — a second criterion smuggled in beside the one that was declared.
            if here.worth_it and (best is None or here.cost < best.cost):
                best = here
        if best is not None and best.complete:
            break          # the smallest set that explains everything; nothing larger is cheaper
    return best if best is not None else nothing


def _choose(pool: Sequence[Observed], size: int) -> List[Tuple[Observed, ...]]:
    from itertools import combinations
    return list(combinations(pool, size))
