"""NYXARA · njp/generatorschool.py — did it find structure, or find structure in noise (🌱).

Five families of transformations, handed over as **behaviour only** — rows in, rows out, no names,
no parameterisation, nothing said about where any of them came from. Two of the five have no
compact description at all, and coming back empty on those is the harder half of the exam: a
search that always produces generators would produce them for noise, and 184 bits against 192 is
exactly what that looks like from inside.

======================  ====================================================================
family                   what is true of it
======================  ====================================================================
turns                    every member is a repeat of one of them. One generator.
turns and a flip         two, and neither is enough on its own.
swaps of neighbours      generated by few, but not by one — the exam's middle case.
unrelated                eight permutations with nothing in common. **Nothing must be found.**
not rearrangements       transformations that add and average rather than move. Not describable
                         this way at all, and saying so is the answer.
======================  ====================================================================

And the accounting V.89 started is carried forward, because a generating set is exactly the kind of
claim that flatters: ``invented`` for structure that is really there, ``flattered`` for structure
found in a family that has none, ``buried`` for a family with structure that came back empty.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

from nyxara.njp.generators import (WIDTH, Description, describe, longhand, watch_behaviour)

__all__ = ["FAMILIES", "Case", "KNOWN", "retrodict", "examine", "run", "SEED"]

SEED = 94


def _turn(k: int) -> Callable[[Sequence[float]], List[float]]:
    return lambda row: [row[(i + k) % WIDTH] for i in range(WIDTH)]


def _flip(row: Sequence[float]) -> List[float]:
    return list(reversed(row))


def _swap_neighbours(at: int) -> Callable[[Sequence[float]], List[float]]:
    def _run(row: Sequence[float]) -> List[float]:
        out = list(row)
        out[at], out[(at + 1) % WIDTH] = out[(at + 1) % WIDTH], out[at]
        return out
    return _run


def _turns() -> List[Any]:
    return [watch_behaviour(_turn(k)) for k in range(WIDTH)]


def _turns_and_a_flip() -> List[Any]:
    seen = [watch_behaviour(_turn(k)) for k in range(WIDTH)]
    seen += [watch_behaviour(lambda r, k=k: _flip(_turn(k)(r))) for k in range(WIDTH)]
    return [s for s in seen if s is not None]


def _neighbour_swaps() -> List[Any]:
    return [watch_behaviour(_swap_neighbours(i)) for i in range(WIDTH - 1)]


def _unrelated() -> List[Any]:
    rng = random.Random(SEED)
    out = []
    for _ in range(WIDTH):
        order = list(range(WIDTH))
        rng.shuffle(order)
        out.append(tuple(order))
    return out


def _not_rearrangements() -> List[Any]:
    """Transformations that add and average. Nothing here moves a value from one place to another.

    ``watch_behaviour`` returns ``None`` for every one of them, which is the honest report: this
    whole way of describing a transformation does not apply, and the module says so rather than
    producing a description of something it did not understand.
    """
    kinds = [lambda r: [v + 1.0 for v in r],
             lambda r: [(a + b) / 2 for a, b in zip(r, list(r[1:]) + list(r[:1]))],
             lambda r: [v * v for v in r],
             lambda r: [max(r)] * len(r)]
    return [watch_behaviour(k) for k in kinds]


FAMILIES: Dict[str, Callable[[], List[Any]]] = {
    "turns": _turns,
    "turns and a flip": _turns_and_a_flip,
    "swaps of neighbours": _neighbour_swaps,
    "unrelated": _unrelated,
    "not rearrangements": _not_rearrangements,
}


@dataclass
class Case:
    name: str = ""
    #: How many generators the family really needs, or 0 when nothing should be found.
    generators: int = 0
    #: Does this family even admit this kind of description?
    describable: bool = True
    note: str = ""


KNOWN: Tuple[Case, ...] = (
    Case("turns", 1, True, "every member is a repeat of one of them"),
    Case("turns and a flip", 2, True, "two, and neither is enough on its own"),
    Case("swaps of neighbours", 0, True,
         "structure exists but no small set reaches it within the depth allowed"),
    Case("unrelated", 0, True, "nothing in common; coming back empty is the answer"),
    Case("not rearrangements", 0, False,
         "these add and average, so the whole way of describing them does not apply"),
)


def retrodict() -> Dict[str, Any]:
    """Describe every family and compare against what is true by construction."""
    rows: List[Dict[str, Any]] = []
    right = flattered = buried = 0
    for case in KNOWN:
        seen = FAMILIES[case.name]()
        usable = [s for s in seen if s is not None]
        unreadable = sum(1 for s in seen if s is None)
        got: Optional[Description] = describe(usable) if usable else None
        found = len(got.generators) if got else 0
        ok = (found == case.generators) if case.describable else (unreadable == len(seen))
        right += int(ok)
        if case.generators == 0 and found > 0:
            flattered += 1
        if case.generators > 0 and found == 0:
            buried += 1
        rows.append({"family": case.name, "want": case.generators, "got": found,
                     "describable": case.describable, "unreadable": unreadable,
                     "cost": got.cost if got else 0.0,
                     "longhand": longhand(len(usable)) if usable else 0.0,
                     "covered": f"{got.covered}/{got.of}" if got else "—",
                     "note": case.note, "description": got})
    return {"rows": rows, "right": right, "of": len(KNOWN),
            "flattered": flattered, "buried": buried,
            "with_structure": sum(1 for c in KNOWN if c.generators > 0),
            "without": sum(1 for c in KNOWN if c.generators == 0)}


def examine() -> Dict[str, Any]:
    """The exam, with its pass condition written down rather than implied.

    Four conditions. Every family gets its own count. **No** family without structure may produce
    generators, which is what ``flattered`` counts and is the failure that matters — the first
    version of the cost model committed it, finding three generators in eight random permutations.
    None with structure may come back empty. And more of the families must have nothing to find
    than something, or the exam rewards a search that always answers yes.
    """
    got = retrodict()
    got["passes"] = bool(got["right"] == got["of"] and got["flattered"] == 0
                         and got["buried"] == 0 and got["without"] > got["with_structure"])
    return got


def run() -> Dict[str, Any]:  # pragma: no cover — a report
    got = examine()
    for row in got["rows"]:
        want = f"{row['want']}" if row["describable"] else "n/a"
        print(f"  {row['family']:<22} want {want:<4} got {row['got']:<4} "
              f"covered {row['covered']:<8} {row['cost']:>7.0f} bits against "
              f"{row['longhand']:>6.0f} longhand")
    print()
    for row in got["rows"]:
        if row["description"] is not None and row["description"].generators:
            print(row["description"].render())
    print(f"\n  right {got['right']}/{got['of']}, flattered {got['flattered']}, "
          f"buried {got['buried']} — {got['without']} of {got['of']} families have nothing to "
          f"find — passes {got['passes']}")
    return got


if __name__ == "__main__":  # pragma: no cover
    run()
